config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs do
    resources :likes, only: [:create, :destroy]
  end
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
# == Schema Information
#
# Table name: dogs
#
#  id            :integer          not null, primary key
#  name          :string
#  birthday      :datetime
#  adoption_date :datetime
#  description   :text
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  owner_id      :integer
#

class Dog < ApplicationRecord
  has_many_attached :images

  belongs_to :owner,
    foreign_key: :owner_id,
    class_name: :User,
    optional: true

  has_many :likes

  # gem 'order_as_specified' for active record to specify order
  extend OrderAsSpecified
end

app/models/like.rb
# == Schema Information
#
# Table name: likes
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  dog_id     :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :dog
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string
#  email                  :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :dogs,
    foreign_key: :owner_id

  has_many :likes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    # add paginate to update index query to only pick up 5 dogs on each page
    # @dogs = Dog.paginate(:page => params[:page], :per_page => 5)

    @all_dogs = Dog.all

    @dog_likes = @all_dogs.map do |dog|
      current_time = DateTime.now
      hour_ago = DateTime.now - 1.hour
      likes = dog.likes.where('created_at BETWEEN ? AND ?', hour_ago, current_time).length || 0
    end


    @dogs_sorted = []
    # keep track of 0 likes in the last hour to append to end of all dogs_sorted array
    @no_likes = []
    # keep track of dogs with the most likes
    @max_likes= []
    
    i = 0
    while i < @dog_likes.length
      if @dog_likes.length == 1
        @dogs_sorted.push(@all_dogs[i])
        break
      end
      
      if @dog_likes[i] == 0
        @no_likes.push(@all_dogs[i])
      else
        j = i + 1
        current_most_likes = @dog_likes.max
        while j < @dog_likes.length
          if @dog_likes[i] > @dog_likes[j]
            if @dog_likes[i] == current_most_likes
              @max_likes.unshift(@all_dogs[i])
            else
              @dogs_sorted.unshift(@all_dogs[i])
            end
            if @dog_likes[j] != 0
              @dogs_sorted.push(@all_dogs[j])  
            end 
          elsif @dog_likes[i] < @dog_likes[j]
            if @dog_likes[j] == current_most_likes
              @max_likes.unshift(@all_dogs[j])
            else
              @dogs_sorted.push(@all_dogs[j])
            end
            @dogs_sorted.push(@all_dogs[i])
          end

          j += 1
        end
      end

      i += 1
    end

    # add all arrays together to have array of dog objects in order of most likes in last hour
    @dogs_sorted = @max_likes + @dogs_sorted + @no_likes

    @dogs = Dog.order_as_specified(:id => @dogs_sorted.each{|dog| dog.id}).paginate(:page => params[:page], :per_page => 5)

  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
    @dog = Dog.find(params[:id])
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = Dog.new(dog_params)
    
    if current_user
      @dog.owner_id= current_user.id
    end

    respond_to do |format|
      if @dog.save
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update

    respond_to do |format|
      if @dog.update(dog_params)
        @dog.images.attach(params[:dog][:image]) if params[:dog][:image].present?

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description, :images)
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new

    render 'dogs/likes/new'
  end

  def create
    @like = current_user.likes.new(dog_id: params[:dog_id])
    @dog = Dog.find(params[:dog_id])
     

    if current_user.likes.where(dog_id: params[:dog_id]).length == 0
      @like.save
      respond_to do |format|
        format.html { redirect_to @dog, notice: 'Like was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      end
    else
      respond_to do |format|
        format.html { redirect_to @dog, notice: 'Already liked this dog, cannot like more than once' }
        format.json { render json: @like.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @like = current_user.likes.where(dog_id: params[:dog_id])[0]
    @dog = Dog.find(params[:dog_id])

    if @like
      @like.destroy
      respond_to do |format|
        format.html { redirect_to @dog, notice: 'Like was successfully unliked.' }
        format.json { render :show, status: :created, location: @dog }
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<%= simple_form_for @dog do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :images, as: :file, :input_html => { multiple: true } %>
  <% if current_user %>
    <% f.input :owner_id, as: :text, :input_html => { value: "#{current_user.id}" } %>
  <% end %>
  

  <% if @dog.images.any? %>
    <%= image_tag @dog.images.first %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<div class="dog-index">
  <a href="<%= url_for(dog) %>">
    <article>
      <h2 class="dog-name"><%= dog.name %></h2>
      <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
    </article>
  </a>
  
  <% current_time = DateTime.now %>
  <% hour_ago = DateTime.now - 1.hour %>
  <h3 class="dog-like-count">
    <% like_count = dog.likes.where('created_at BETWEEN ? AND ?', hour_ago, current_time).length %>
    <% if like_count == 1 %>
      <%= like_count %> like in the last hour
    <% else %>
      <%= like_count %> likes in the last hour
    <% end %>
  </h3>
</div>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<%= will_paginate @dogs %>
<%# render partial: 'thumbnail', collection: @dogs, as: :dog %>
<% @dogs.each_with_index do |dog, idx| %>
  <%= render partial: 'thumbnail', locals: {dog: dog} %>
  <% if (idx + 1) % 2 == 0 %>
    <img class="ad" src="ad.jpg" alt="collar">
  <% end %>
<% end %>
<%= will_paginate @dogs %>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <div class="dog-images">
    <% @dog.images.each do |image| %>
      <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
    <% end %>
  </div>

  <p><%= @dog.description %></p>

  <% if current_user %>
    <% if current_user.dogs.where(id: params[:id]).length != 0 %>
      <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
      <br>
      <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% else %>
      <% current_like = current_user.likes.where(dog_id: @dog) %>
      <% if current_like.length == 1 %>
        <%= link_to "Unlike #{@dog.name}", dog_like_path(@dog, current_like.first), method: :delete %>
      <% else %>
        <%= link_to "Like #{@dog.name}", dog_likes_path(@dog), method: :post %>
      <% end %>
    <% end %>
  <% else %>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div class="greeting">
        <% if current_user %>
          Hello <%= current_user.name %>
        <% end %>
      </div>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>